default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

development:
  <<: *default
  database: furima_46639ver2_development
  username: <%= ENV["PGUSER"] || ENV["USER"] || "postgres" %>
  # host/port/password は未記載（←ソケット接続でパスワード不要）

test:
  <<: *default
  database: furima_46639ver2_test
  username: <%= ENV["PGUSER"] || ENV["USER"] || "postgres" %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>